export enum UserActivityAction {
  ACCOUNT_CREATED = 'ACCOUNT_CREATED',
  PROFILE_UPDATED = 'PROFILE_UPDATED',
  USER_UPDATED = 'USER_UPDATED',
  ROLE_CHANGED = 'ROLE_CHANGED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  USER_DELETED = 'USER_DELETED',
  PASSWORD_CHANGED = 'PASSWORD_CHANGED',
  PASSWORD_RESET = 'PASSWORD_RESET',
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
}
